[package]
name = "xml-rs"
version = "0.1.23"
authors = ["Vladimir Matveev <vladimir.matweev@gmail.com>"]
license = "MIT"
description = "An XML library in pure Rust"
repository = "https://github.com/netvl/xml-rs"
documentation = "http://netvl.github.io/xml-rs/"

[lib]
name = "xml"
path = "src/lib.rs"

[dependencies]
bitflags = "*"
