[package]
name = "xml-rs"
version = "0.1.4"
authors = ["Vladimir Matveev <vladimir.matweev@gmail.com>"]
license = "MIT"
description = "An XML library in pure Rust"

[lib]
name = "xml"
path = "src/lib.rs"
